Add fault tolerance for API reading
Cause:

org.droidmate.device.android_sdk.ApkExplorationException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
	at org.droidmate.tools.ApkDeployer.withDeployedApk(ApkDeployer.kt:66)
	at org.droidmate.command.ExploreCommand$deployExploreSerialize$1.invoke(ExploreCommand.kt:332)
	at org.droidmate.command.ExploreCommand$deployExploreSerialize$1.invoke(ExploreCommand.kt:84)
	at org.droidmate.tools.AndroidDeviceDeployer.withSetupDevice(AndroidDeviceDeployer.kt:173)
	at org.droidmate.command.ExploreCommand.deployExploreSerialize(ExploreCommand.kt:316)
	at org.droidmate.command.ExploreCommand.execute(ExploreCommand.kt:298)
	at org.droidmate.command.ExploreCommand.execute(ExploreCommand.kt:228)
	at org.droidmate.frontend.DroidmateFrontend$Companion.execute(DroidmateFrontend.kt:126)
	at org.droidmate.frontend.DroidmateFrontend$Companion.execute$default(DroidmateFrontend.kt:92)
	at org.droidmate.frontend.DroidmateFrontend$Companion.main(DroidmateFrontend.kt:81)
	at org.droidmate.frontend.DroidmateFrontend.main(DroidmateFrontend.kt)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
	at org.droidmate.device.MonitorsClient.getLogs(MonitorsClient.kt:81)
	at org.droidmate.device.TcpClients.getLogs(TcpClients.kt:58)
	at org.droidmate.device.AndroidDevice.readAndClearMonitorTcpMessages(AndroidDevice.kt:273)
	at org.droidmate.device.deviceInterface.ApiLogsReader.getAndClearMessagesFromMonitorTcpServer(ApiLogsReader.kt:98)
	at org.droidmate.device.deviceInterface.ApiLogsReader.access$getAndClearMessagesFromMonitorTcpServer(ApiLogsReader.kt:41)
	at org.droidmate.device.deviceInterface.ApiLogsReader$getAndClearCurrentApiLogsFromMonitorTcpServer$logs$1.invoke(ApiLogsReader.kt:65)
	at org.droidmate.device.deviceInterface.ApiLogsReader$getAndClearCurrentApiLogsFromMonitorTcpServer$logs$1.invoke(ApiLogsReader.kt:41)
	at org.droidmate.device.deviceInterface.ApiLogsReader.readApiLogcatMessages(ApiLogsReader.kt:73)
	at org.droidmate.device.deviceInterface.ApiLogsReader.getAndClearCurrentApiLogsFromMonitorTcpServer(ApiLogsReader.kt:65)
	at org.droidmate.device.deviceInterface.DeviceMessagesReader.getAndClearCurrentApiLogsFromMonitorTcpServer(DeviceMessagesReader.kt:68)
	at org.droidmate.device.deviceInterface.DeviceMessagesReader.getAndClearCurrentApiLogs(DeviceMessagesReader.kt:57)
	at org.droidmate.device.deviceInterface.RobustDevice$getAndClearCurrentApiLogs$1.invoke(RobustDevice.kt:492)
	at org.droidmate.device.deviceInterface.RobustDevice$getAndClearCurrentApiLogs$1.invoke(RobustDevice.kt:49)
	at org.droidmate.device.deviceInterface.RobustDevice.rebootIfNecessary(RobustDevice.kt:407)
	at org.droidmate.device.deviceInterface.RobustDevice.getAndClearCurrentApiLogs(RobustDevice.kt:492)
	at org.droidmate.device.deviceInterface.DeviceLogsHandler._readAndClearApiLogs(DeviceLogsHandler.kt:72)
	at org.droidmate.device.deviceInterface.DeviceLogsHandler.readClearAndAssertOnlyBackgroundApiLogsIfAny(DeviceLogsHandler.kt:48)
	at org.droidmate.exploration.actions.ClickExplorationAction$performDeviceActions$1.doResume(ClickExplorationAction.kt:57)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:244)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:185)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:175)
	at org.droidmate.exploration.actions.ClickExplorationAction.performDeviceActions(ClickExplorationAction.kt:54)
	at org.droidmate.exploration.actions.AbstractExplorationAction.run(AbstractExplorationAction.kt:79)
	at org.droidmate.command.ExploreCommand.explorationLoop(ExploreCommand.kt:412)
	at org.droidmate.command.ExploreCommand.run(ExploreCommand.kt:379)
	at org.droidmate.command.ExploreCommand.tryExploreOnDeviceAndSerialize(ExploreCommand.kt:356)
	at org.droidmate.command.ExploreCommand.access$tryExploreOnDeviceAndSerialize(ExploreCommand.kt:84)
	at org.droidmate.command.ExploreCommand$deployExploreSerialize$1$$special$$inlined$forEachIndexed$lambda$1.invoke(ExploreCommand.kt:333)
	at org.droidmate.command.ExploreCommand$deployExploreSerialize$1$$special$$inlined$forEachIndexed$lambda$1.invoke(ExploreCommand.kt:84)
	at org.droidmate.tools.ApkDeployer.withDeployedApk(ApkDeployer.kt:58)
	... 10 more